---
roles:

collections:
  - name: community.general

  - name: https://github.com/lucaslehnen/tchecode.libvirt.git
    type: git
    version: main

  - name: https://github.com/lucaslehnen/tchecode.vmware.git
    type: git
    version: main
