---
# handlers file for install
- name: Reboot
  reboot:
    msg: "Reboot initiated by Ansible"
  listen: "reboot"

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
  listen: "restart_nginx"