- name: "Install libvirt packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libvirt-daemon
      - qemu-kvm
      - bridge-utils
      - virtinst
      - libvirt-daemon-system
      - libguestfs-tools
      - libosinfo-bin
      - qemu-system
      - virt-manager     

- name: "Loading vhost_net kernel module"
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: vhost_net
    state: present 
  notify: reboot

- name: "Loading kvm_intel kernel module"
  lineinfile:
    path: /etc/modprobe.d/qemu-system-x86.conf
    line: options kvm_intel nested=1
    state: present     
    create: true
  notify: reboot

- name: "Enabling service" 
  service:
    name: libvirtd
    enabled: yes
  notify: reboot

- name: "Starting service" 
  service:
    name: libvirtd
    state: started

- name: "Checking the version"  
  command: virsh version --daemon
  register: version
  changed_when: false

- name: ""
  debug: 
    msg: "{{ version.stdout }}"

- name: "Verificando pool de imagens"
  shell: 
    cmd: 'virsh pool-list --all | grep "imagens"'
  register: check_pool

- name: "Criando o pool de imagens"
  shell: 
    cmd: 'virsh pool-define-as imagens dir - - - - "/var/lib/libvirt/images"'    
  when: check_pool.stdout.find('imagens') < 0

- name: "Iniciando o pool de imagens"
  shell: 
    cmd: 'virsh pool-start imagens'    
  when: check_pool.stdout.find('inativo') >= 0
  