---
# tasks file for iso-cache-server
- name: "Instalando nginx"
  apt:
    name: nginx
    state: present

- name: "Criando o diretório de imagens"
  file:
    path: "/var/www/isos"
    state: directory
    owner: "root"
    mode: 0775            

- name: "Servindo o diretório de imagens no Nginx"
  template:
    src: "nginx_isos.conf.j2"
    dest: "/etc/nginx/sites-available/default"
    force: true    
    mode: preserve 
    backup: true 
  notify: restart_nginx

- name: "Baixando imagens dos mirrors para o servidor local"
  get_url: 
    url: "{{ item.url }}"
    dest: "/var/www/isos/{{ item.url | basename }}"
  with_items: "{{ isos_mirrors }}"  
