- hosts: k3s_cluster
  user: ubuntu
  become: true
  roles:
    - {role: k3s-install, tags: [k3s]}
  vars:
    k3s_version: v1.21.5+k3s1

- hosts: k3s_master
  user: ubuntu
  become: true
  roles:
    - {role: k3s-config-master, tags: [k3s]}
  vars:
    master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
    ansible_user: ubuntu
    extra_server_args: "--write-kubeconfig-mode 644"

- hosts: k3s_worker
  user: ubuntu
  become: true
  roles:
    - {role: k3s-config-worker, tags: [k3s]}
  vars:
    master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0]) }}"
    extra_agent_args: ""
